services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=Pierrot'
      - 'MYSQL_ROOT_PASSWORD=Galerien3?'
      - 'MYSQL_USER=Pierrot'
    ports:
      - '3308:3306'
    volumes:
      - './mysql-files:/var/lib/mysql'
