services:
  mysql:
    image: 'mysql:9.5'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
    ports:
      - '${MYSQL_PORT:-3308}:3306'
    volumes:
      - './mysql-files:/var/lib/mysql'
